# memory
spring:
  datasource:
    url: jdbc:h2:mem:product;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        show_sql: false
        use_sql_comments: false
        format_sql: false
        type: false
  sql:
    init.mode: always

cors-origin: http://localhost:4200

# logging:
#   level:
#     org:
#       springframework: DEBUG
#       hibernate:
#         SQL: TRACE
#         type: TRACE

management:
    endpoints:
        web:
            exposure:
                include: "*"
    metrics:
        export:
            prometheus:
                enabled: true