# dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        show_sql: false
        use_sql_comments: false
        format_sql: false
        type: false
  sql:
    init.mode: always

cors-origin: http://localhost:4200

logging:
  level:
    org:
#       springframework: DEBUG
#       hibernate:
#         SQL: TRACE
#         type: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true